slack-java-client/src/main/java/com/hubspot/slack/client/SlackClientModule.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClientRuntimeConfigIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/http/NioHttpClient.java

Exposes the underlying http configuration, so users can change the behavior here.

Allow customization of http config

---

slack-base/src/main/java/com/hubspot/slack/client/models/users/UserProfileIF.java

Jackson doesn't consider numbers a new token so it doesn't understand the underscore in the image URLs in `UserProfile`. This adds explicit `@JsonProperty` annotations to work around this behavior.

properly deserialize image url

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/concurrency/CloseableExecutorService.java
slack-java-client/src/main/java/com/hubspot/slack/client/concurrency/FollowThreadLocalsExecutorService.java
slack-java-client/src/main/java/com/hubspot/slack/client/concurrency/FollowThreadsMixin.java
slack-java-client/src/main/java/com/hubspot/slack/client/concurrency/LoggingUncaughtExceptionHandler.java
slack-java-client/src/main/java/com/hubspot/slack/client/concurrency/MoreExecutors.java
slack-java-client/src/main/java/com/hubspot/slack/client/concurrency/ThreadContextFollower.java
slack-java-client/src/main/java/com/hubspot/slack/client/concurrency/ThreadContextHook.java
slack-java-client/src/main/java/com/hubspot/slack/client/concurrency/ThreadFactories.java
slack-java-client/src/main/java/com/hubspot/slack/client/http/NioHttpClient.java

By default `thenCompose` executes in the calling thread, which really doesn't work in this case. The trick is to add an unbounded default size zero thread pool to handle the chained call -- we'll spawn a thread to handle the recursing (basically just to wait). In general this pool will idle empty (since min size is 0), and can expand for heavy use. Since we're heavily rate limited, threads won't be an issue here, and we make sure to clean up.
I ported our internal executor wrappers here to ensure that it's closeable and we clean up after ourselves.

Don't #thenCompose in the same thread

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/conversations/ConversationOpenParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/conversations/ConversationsOpenResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

This adds support for the [conversation.open](https://api.slack.com/methods/conversations.open) method.
@szabowexler

Add open conversation method

---

slack-base/src/main/java/com/hubspot/slack/client/models/AttachmentIF.java

Adds support for the `thumb_url` field on attachments https://api.slack.com/docs/message-attachments
@szabowexler

add support for thumb url

---

slack-base/src/main/java/com/hubspot/slack/client/models/auth/OAuthCredentialsIF.java

Slack's new [Workspace Token Auth](https://api.slack.com/docs/working-with-workspace-tokens) has a slightly different OAuth contract. Mainly, it doesn't send back the `scope` or `user_id` fields so those need to be optional here.
cc @darcatron

support WTA in OAuthCredentials

---

slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionIF.java

https://api.slack.com/dialogs
> Provide up to 100 options. Either options or option_groups is required for the static and **external.options[].label is a user-facing string for this option. 75 characters maximum.** Required.options[].value is a string value for your app. If an integer is used, it will be parsed as a string. 75 characters maximum. Required.

update label limit

---

slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackDialogFormTextElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormTextElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormTextareaElement.java

`500` is not the default max for both `text` and `textarea` fields. This updates the validation to verify `text` < 150 and `textarea` < 3000. I also threw in the checks for min values
Note: [Slack's documention](https://api.slack.com/dialogs) is inconsistent for `text` values. For max_length, they mention 
> Maximum input length allowed for element. Up to 150 characters. Defaults to 150
and then the docs say
> A default value for this field. Up to 500 characters
for `value`
I left it all as 150 just to be safe. Will do a quick local test to see if `500` works for `text` and update this PR

update max char checks

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java

`MAPPER.writeValueAsString(SlackError.builder().setError("not_authed").build());` outputs
```json
{"type":"NOT_AUTHED","error":"not_authed"}
```
Trying to deserialize that means `fromCode` is called with `code = NOT_AUTHED`. This causes the lookup to default to `SlackErrorType.UNKNOWN`. 🙅 
Added an index for the keys. It'll now check that first and if it fails, it'll check the codes and default to unknown nothing is found
Tested locally and it looks good

allow deserialization if 'type' is included in json

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatPostEphemeralMessageParamsIF.java

slack defaults to "none" which means:
> If you don't want Slack to perform any processing on your message, pass an argument of parse=none
We should default to `none` as well. `full` means
> If you want Slack to treat your message as completely unformatted, pass parse=full. This will ignore any markup formatting you added to your message.
which is very confusing since references to channels and users would render as strings. that's rarely what a user would want
cc @szabowexler

don't perform processing by default

---

slack-base/src/main/java/com/hubspot/slack/client/models/TopLevelMessageResponseType.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackDialogFormTextElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/TopLevelMessageInteractionResponseIF.java

This allows users to respond to interactions right away with a [top level slack message](https://api.slack.com/docs/interactive-message-field-guide#message)
This is most useful for message interactions where you want to replace or delete the original message based on an interaction
Tested this locally
cc @szabowexler

add support for top level message

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/files/FilesUploadParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileTypes.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackGifFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackImageFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackTextFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/files/FilesUploadResponseIF.java
slack-base/src/test/java/com/hubspot/slack/client/TestMappers.java
slack-base/src/test/java/com/hubspot/slack/client/models/response/SlackFileUploadResponseTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/response/SlackResponseTest.java
slack-base/src/test/resources/file_upload_content_param_result.json
slack-base/src/test/resources/file_upload_gif_result.json
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Per the description, adds support for calling [`files.upload`](https://api.slack.com/methods/files.upload). This isn't complete (no support for `mime/multipart` right now), but allows a user to upload a block of text (i.e. creating a snippet). The class structure here is permissive, and makes it easy to add additional filetype wrappers (I've added image based (gif) file handles as well as the core text to make the eventual extension to mime simpler). Once I've tested it in the wild I'll merge.
@darcatron

Add basic support for uploading files

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/files/FilesSharedPublicUrlParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/files/FilesSharedPublicUrlResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

What it says on the tin. Adds support for [`files.sharedPublicURL`](https://api.slack.com/methods/files.sharedPublicURL). Since file uploads are (by default) not shared, you need to be able to share them with the world to actually send links to folks.

Add support for sharing file publically

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/AbstractChatPostMessageParams.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatPostEphemeralMessageParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatUpdateMessageParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/MessageParams.java
slack-base/src/test/java/com/hubspot/slack/client/ReflectionBasedFieldPresenceTest.java
slack-base/src/test/java/com/hubspot/slack/client/methods/params/chat/MessageParamsTest.java

Resolves: https://github.com/HubSpot/slack-client/issues/21
Tested locally and the functionality works. 
I tried having the check within the parent `MessageParams` but I got test failures like:
```
pojosDoDeserializeHasChannelsWithChannelField[class com.hubspot.slack.client.methods.params.chat.ChatUpdateMessageParams](com.hubspot.slack.client.HasChannelDeserializerTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.reflect.InvocationTargetException
```
The current build for this is causing similar problems. It's hitting the `@Check` and erroring on the test
Any thoughts on this @szabowexler ?

allow empty text field if attachments are provided

---

slack-java-client/src/main/java/com/hubspot/slack/client/interceptors/http/HttpFormatter.java
slack-java-client/src/test/java/com/hubspot/slack/client/interceptors/http/HttpFormatterTest.java

This is a follow up to #50, and extends the same redaction behavior to `token` auth via a query param.

Also perform redaction of raw token included in query param

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

The default rate limiter throttles in _seconds_ not milliseconds. Very important to log this right. 
I've also dropped log warning time to 5 seconds since 5 seconds is a long API call. Worthwhile to know if it's waiting that long

seconds not milliseconds

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackClientRuntimeConfigIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/ratelimiting/ByMethodRateLimiter.java
slack-java-client/src/main/java/com/hubspot/slack/client/ratelimiting/SlackRateLimiter.java

1. Defined a new SlackRateLimiter interface with one method, acquire(String slackToken, SlackMethod slackMethod) which acquires a permit for the given token method combination
2. Defined an implementation ByMethod, which encapsulates the current rate limiting implementation in SlackClient (i.e. the static map of RATE_LIMITERS from method to guave RateLimiter)
3. Adds an option on SlackRuntimeConfig to specify a rate limiter
4. Inject the new ByMethodRateLimiter in SlackWebClient, use it if slackRuntimeConfig.getSlackRateLimiter() is empty
**Testing**
Tested locally by building off branch in slack-integration and running the updateSlackChannels job, which uses Slack Client. Job operated as expected

Allowing custom rate limiters on the slack client

---

slack-base/src/main/java/com/hubspot/slack/client/models/ChannelType.java
slack-base/src/main/java/com/hubspot/slack/client/models/SlackChannelIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/user/SlackMemberJoinedChannelEventIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/events/json/EventDeserializerTest.java
slack-base/src/test/resources/member_joined_private_channel.json

Also updated SlackChannel to use the new slack channel type name -> ChannelType mapping
**Testing**
Added unit test for deserializing private channel

Made SlackMemberJoinedChannelEvent deserialize ChannelType to an enum value directly

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java
slack-java-client-examples/pom.xml

add user_not_found to error type list

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/DialogSubmissionIF.java

Implementing changes from https://github.com/HubSpot/slack-client/pull/80
The dialog submission also contains the state that was passed through when it was created.

Adding state to dialog submission

---

slack-base/src/main/java/com/hubspot/slack/client/models/dialog/SlackDialogIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackJpgFileIF.java

\closes https://github.com/HubSpot/slack-client/issues/76
However, we would want to maybe consider a different implementation in order to add all the file types here https://api.slack.com/types/file ?

Adding JPG file type

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/AbstractSlackEventMessage.java

If a bot posts in a DM, the slack event message that gets posted does not have the BOT_MESSAGE subtype, but instead includes the bot_id. 
E.g. of a _raw_ event - this was sent by a bot in a DM to a (non-bot) user:
```
2019-03-11 15:01:23.934 [dw-122 - POST /wall-e/events] INFO  c.h.p.resources.SlackEventResource - 
Received event {
"token":"[...]",
"team_id":"TEAM123",
"api_app_id":"APP123",
"event":
{"bot_id":"BOT123",
"type":"message",
"text":":wave: Please post links to relevant logs. An engineer will respond soon.",
"user":"USER123",
"ts":"1552330883.013000",
"attachments":[...],
"thread_ts":"1552330877.012800",
"parent_user_id":"USER234",
"channel":"CHAN123",
"event_ts":"1552330883.013000",
"channel_type":"channel"},
"type":"event_callback",
"event_id":"Event123", …
```

The bot_id is sometimes included in a message that doesn't have the BOT_MESSAGE subtype

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorResponseIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/response/SlackResponseTest.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Sometimes the slack API is returning a list of `errors` instead of `error`. While not perfect, this causes the client to not break on that response.

handle "errors" instead of "error" in response

---

DEV_README.md
README.md

The following is a **proposed** plan on how to find and handle "breaking changes".
I'm happy to make any changes to the frequency or process when we find a possible issue. The main thing I wanted to provide was a way for us to be proactive and prevent our slack client from breaking in the future due to a foreseeable change.

Updating README to reference 'breaking changes' guidelines.

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java

We've seen the error `cannot_dm_bot` come through when trying to DM a bot. This error is undocumented so we reached out to Slack to understand the issue. They said
> It would appear that the error cannot_dm_bot is thrown because a dm between two bots can not exisit. If the im.open method is being called with a bot token xoxb then this is likely the reason.
I tested this and was able to reproduce this by utilizing an authorized bot token (xoxb-*) and hitting `im.open` for a bot user ID. Note: this only appears if using a bot token provided during the install authorization. It cannot be the bot token listed in the app's "OAuth & Permissions" page. If the app's "OAuth & Permissions" bot token is used, we see "user_not_found."

add cannot_dm_bot error

---

slack-base/src/main/java/com/hubspot/slack/client/models/LiteMessageIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackPngFileIF.java

When issues a find replies request, files come back. This exposes them, and adds PNG support.

Expose file

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackUnknownFiletypeIF.java

This is a followup to #93. That PR inadvertently broke users, because we don't have complete support for the [full list of Slack filetypes](https://api.slack.com/types/file). In this PR, we add a default deserializer that exposes the core set of attributes we know every file will have. This can be expanded in the future by adding explicit support for desired files for deserialization, but this here will ensure there are no runtime exceptions on new files.

Add a default parser to handle unknown/unsupported filetypes without breaking

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java

Internal testing has found some cases where these fields are not present on the response payload.

These are not always present on files

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackUnknownFiletypeIF.java

Follow up to #95 and #94. Basically there's huge variance in what fields are actually present, which can lead to strange runtime exceptions when you hit new file types. 
This PR adds default values for basically everything, which should mean that the unknown file type effectively can't fail to parse.

Make default have sentinel values for EVERYTHING

---

slack-java-client-examples/src/main/java/com/hubspot/slack/client/examples/CustomDebugConfig.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/interceptors/http/DefaultHttpResponseDebugger.java
slack-java-client/src/main/java/com/hubspot/slack/client/interceptors/http/ResponseDebugger.java
slack-java-client/src/test/java/com/hubspot/slack/client/SlackWebClientTest.java

The current rate limiter implementation asks, "when can we send a request" rather than "should we send a request." There's no easy way to proactively stop a request from going out if we know it'll fail. With the current implementation, we must either wait until the request can be sent (bad for high throughput services) or throw an exception (not ideal).
This PR adds support for returning a value to indicate the request was proactively rate limited. Proactively rate limiting means the request won't go out to Slack and the method caller can handle the rate limit just as they would have if Slack had actually rate limited.
@mindspin311 
@igorushakov
cc @szabowexler

allow proactive rate limiting

---

slack-base/src/main/java/com/hubspot/slack/client/methods/SlackMethods.java

I wrote up a job to resolve https://github.com/HubSpot/slack-client/issues/58. The first run lead to these fixes. We'll continue running it internally and make updates as necessary.
Note: we only check what's already defined in the enum list. We don't check new methods Slack may have added that aren't declared on the enum list. 
@mindspin311 @igorushakov

correct methods and tiers

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventType.java
slack-base/src/test/java/com/hubspot/slack/client/models/events/json/EventDeserializerTest.java
slack-base/src/test/resources/app_mention_message.json

This pr adds support for the `app_mention` event type as [documented here](https://api.slack.com/events/app_mention). The app mention event is useful for limiting calls to a bot service to only when the bot/app is explicitly mentioned. 
I've made the structure match the message event because, according to the docs, they are interchangeable:
> `app_mention` events are just like other message events sent over the Events API, but their type indicates `app_mention`.

Add APP_MENTION event type

---

README.md
slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventType.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/links/LinkIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/links/SlackLinkSharedEventIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/events/json/EventDeserializerTest.java
slack-base/src/test/resources/link_shared.json
slack-base/src/test/resources/link_shared_with_thread_ts.json

Adds support for [link_shared](https://api.slack.com/events/link_shared) events from the Slack Events API. 
Slack sends this event over the Events API for Slack apps set up to track a specific URL domain

Adds support for link_shared events

---

slack-base/src/main/java/com/hubspot/slack/client/models/MessageIF.java

Fixes #109. Tested in production.
However, it's potentially a breaking change.
Please advise if some extra measures should be taken.

Messages from search may not have a user

---

slack-base/src/main/java/com/hubspot/slack/client/models/LiteMessageIF.java

Slack quietly (but effectively) broke their public API by adding some relatively undocumented fields. If you look at their [WYSIWYG](https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less) announcement, it lays out that they will be adding a `rich_text` field that has `rich_text_section` that can include other, even undocumented(!), elements.
Until we can figure this out, this change makes the block field on the lite message class optional so we won't fail to deserialize magical unknown fields.

Temporarily ignore blocks on serde

---

slack-base/src/main/java/com/hubspot/slack/client/models/SlackChannelIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/conversations/ConversationIF.java

Add support for the `is_private` and `is_member` fields on the channel/conversations response.

Add is_private and is_member fields to channel/conversation

---

slack-base/src/main/java/com/hubspot/slack/client/models/LiteMessageIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/Block.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/UnknownBlock.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/BlockElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/UnknownBlockElement.java
slack-base/src/test/java/com/hubspot/slack/client/models/blocks/BlockSerializationTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/blocks/elements/BlockElementSerializationTest.java
slack-base/src/test/resources/unknown_block_element.json
slack-base/src/test/resources/unknown_blocks.json

Handle unknown block and block element types by having a default Unknown type for each.
On [this page](https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less), Slack have said:
> Expect to encounter other (even undocumented) elements.
Therefore, we will likely never know beforehand the entire list of blocks and block elements that may be returned, so this is our mechanism for handling unknown types.

Handle unknown block and block element types

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ExternalMultiSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/StaticMultiSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/StaticSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/json/OptionOrOptionGroupDeserializer.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/objects/ConfirmationDialogIF.java
slack-base/src/test/resources/block_elements.json

Similar to `ImageBlockOrText`, add a custom deserialiser to handle `OptionOrOptionGroup`
Fixes #130

#130: Add a custom deserialiser for OptionOrOptionGroup, so that it is deserialised correctly.

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ButtonIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ChannelSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ChannelsMultiSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ConversationSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ConversationsMultiSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/DatePickerIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ExternalMultiSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ExternalSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/HasActionId.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/OverflowMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/PlainTextInputIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/RadioButtonGroupIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/StaticMultiSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/StaticSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/UserSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/UsersMultiSelectMenuIF.java

Even though the Slack API docs say that when an user select's a menu, the interaction's value should arrive in the "value" field, I believe the docs are incorrect and reality is different.
Specifically, what I am seeing in the real world is that select menus will have their value arrive instead as a "selected_option" field. Thus, this deserializer will inspect for this field and pull the value from there if present.

common interface for BlockElements that also have an action_id

---

slack-base/src/main/java/com/hubspot/slack/client/models/LiteMessageIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/util/AbstractSlackReplyMessage.java
slack-base/src/test/java/com/hubspot/slack/client/models/response/conversations/ConversationsRepliesResponseTest.java

This removes the warnings about getReplies() being deprecated. I was finding that it was firing even thought I wasn't calling it, I believe because Jackson serialization was tickling the method. Rather than try to solve that issue, I realized that because the functionality has since been removed (October 2019), it probably makes sense to just delete it. 
If you agree, here is the PR.
If not, I'd like to figure out a way to get the warnings to stop :)

removes logging for deprecated field that has since been removed

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventType.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/bot/SlackAppHomeOpenedEventIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/events/json/EventDeserializerTest.java
slack-base/src/test/resources/app_home_opened.json

This little patch moves the app_home_opened incoming event from the realm of being unknown (SlackEventType.UNKNOWN) and thus turned into a simple SlackEventSkeleton object to something more useful: a full blown SlackAppHomeOpenedEvent that contains the current view payload.
PS: Not sure if the package name "bot" or "views" would have been better.

app_home_opened event support

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java

Slack is going to take these away at the end of the year. Make clear that they're deprecated.

Mark deprecated methods

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatPostEphemeralMessageParamsIF.java

Fixes #147. Slack changed their API in a way that works for legacy and fails for new apps. Thanks Slack. I'll need to test this to verify it doesn't immediately break usages, but once I've done that it should resolve this class of issue.

Allow explicit setting of as_user for legacy, but don't include if unset for new apps

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/AbstractChatMessageParams.java

Slack has updated their API for V2 apps, and the as_user option will be rejected by V2 apps trying to use it. We can simply not serialize this field if it is not set, since it is optional.
To see more about Authorship https://api.slack.com/methods/chat.postMessage#authorship

Don't serialize an absent value on as_user API option

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java

This one is returned by https://api.slack.com/methods/conversations.invite method.

Add "already_in_channel" error type

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/conversations/ConversationSetPurposeResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/conversations/ConversationSetTopicResponseIF.java

As it turns out, Slack documentation is outdated and these APIs return another response format so we fail to parse JSON response to java model. I removed `topic` and `description` to be able to parse the response successfully.
- https://api.slack.com/methods/conversations.setTopic
- https://api.slack.com/methods/conversations.setPurpose
Response format specified in docs:
```
{
"ok": true,
"purpose": "I didn't set this purpose on purpose!"
}
```
Actual response format:
```
{
"ok": true,
"channel": {
"id": "XXXXXX",
"name": "xxx",
"is_channel": true,
"is_group": false,
"is_im": false,
"created": 1586792508,
"is_archived": false,
"is_general": false,
"unlinked": 0,
"name_normalized": "xxxx",
"is_shared": false,
"parent_conversation": null,
"creator": "XXXXXX",
"is_ext_shared": false, …
```

Fix purpose and topic response models

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/InteractiveCallbackType.java
slack-base/src/test/java/com/hubspot/slack/client/models/interaction/SlackInteractiveCallbackTest.java

@szabowexler @johnnyleitrim 
Adds a proper mapping for `VIEW_SUBMISSION`. The object was being properly parsed, but the enum didn't exist. This PR adds the enum in and adds a tests that should automatically ensure that the json subtypes always maps the relevant enum type in the future.

Add enum mapping for view_submission interactive callback

---

slack-base/src/main/java/com/hubspot/slack/client/models/users/ProfileFieldIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/users/UserProfileIF.java
slack-base/src/test/resources/deleted_slack_user.json

These don't appear to be documented but do appear to exist. AFAICT its a `Map<String, ProfileField>`.
For  us for example we've got the actual username of the user in here, as well as other visible / non-visible custom profile data. 
Example redacted data:
```json
{
"fields": {
"X000000000": {
"value": "",
"alt": ""
},
}
}
```

User profile fields

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackClientRuntimeConfigIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Adds the option to construct your own `NioHttpClient` for reuse among many slack client wrappers. Helps address #170 
NOTE: if you pass in your own client like this, you own closing it down.

Allow a user to specify the http client and we'll just reuse that

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Added method to get one list of conversations paged using [conversations.list](https://api.slack.com/methods/conversations.list) Slack API.

Add method to get paginated conversations

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventType.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/user/SlackMemberLeftChannelEventIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/events/json/EventDeserializerTest.java
slack-base/src/test/resources/member_left_private_channel.json
slack-base/src/test/resources/member_left_public_channel.json

Need to deal with [member_left_channel](https://api.slack.com/events/member_left_channel) Slack event. Added model for it.

Add model for Slack member_left_channel event

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Added method to get user.conversations with pagination to be able to handle rate limit errors in slack HubsSpot integration.

Add method to get paginated user.conversations

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

`getConversationMembersPaginated` added in order to be able to fetch conversation members with rate limit exception handling (retry). Needed for HS-Slack integration project.

Add SlackClient method to fetch conversation members paginated

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/conversations/ConversationsInfoParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/conversations/ConversationIF.java

Need to fetch Slack channel members count to display it on CRM card. 
Docs: https://api.slack.com/methods/conversations.info

Add param to fetch channel members count in conversations.info

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/users/UsersProfileResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

This adds a method to the `SlackClient` to get the UserProfile using [users.profile.get](https://api.slack.com/methods/users.profile.get) Slack API.
Also adds a model to handle the response.
This is required for getting UserProfile fields in a new automation [(PR).](https://git.hubteam.com/HubSpot/Kepler/pull/1867)

Adding a method to SlackClient to get UserProfile

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/SectionIF.java

Slack's documentation states:
> The text for the block, in the form of a text object. Maximum length for the text in this field is 3000 characters. This field is not required if a valid array of fields objects is provided instead.
This PR allows you to either set text, or just provide a list of fields.

Update to reflect that you can build a section with nothing but fields

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatPostEphemeralMessageParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatUpdateMessageParamsIF.java

Small update to make update/post ephemeral messages also allow sending pure attachment/block kit messages.

Allow empty text if there is a list of attachments or blocks

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlocksLoadOptionsResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/InteractiveCallbackType.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/ShortcutIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/SlackInteractiveCallback.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewDatePickerIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewPlainTextInputIF.java

Apologies in advance for the duplicate commits -- I screwed up my branch, but I think this will all merge fine once you get the other PR merged to master.
This change is just two small tweaks: I found that `ViewDatePickerIF` and`ViewPlainTextInputIF` could have null values in the real world. Per our previous discussion, I made these `Optional` since I figure the breaking change would be much smaller since it was two leaf node interfaces.

Optional view input values for ViewDatePickerIF and ViewPlainTextInputIF

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlocksLoadOptionsResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/InteractiveCallbackType.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/ShortcutIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/SlackInteractiveCallback.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/TopLevelMessageInteractionResponseIF.java

Apologies in advance for the duplicate commits -- I screwed up my branch, but I think this will all merge fine once you get the other PR merged to master.
This PR is just a simple addition of `List<Block> getBlocks();` to `TopLevelMessageInteractionResponseIF` reflecting the reality that in addition to text or attachments, the response can also contain blocks.

TopLevelMessageInteractionResponseIF can contain blocks

---

slack-base/src/main/java/com/hubspot/slack/client/models/auth/OAuthV2CredentialsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/teams/SlackTeamLiteIF.java

Object added in order to be able to deserialize response for [oauth.v2.access](https://api.slack.com/methods/oauth.v2.access) request which is used on Slack app installation to exchange temporary OAuth code for an API access token.

Add OAuth credentials object for v2 Slack app

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatPostEphemeralMessageParamsIF.java

V2 Slack app doesn't support `as_user` param for chat.postEphemeral method.  
Here is the error:
```
{
"ok" : false,
"error" : "invalid_arguments",
"deprecated_argument" : "as_user",
"warning" : "missing_charset",
"response_metadata" : {
"warnings" : [ "missing_charset" ]
}
```
This PR adds annotation to not include `as_user` param if it's value is not present. It'll be treated as `false` in such case.
Please see also:
https://api.slack.com/authentication/quickstart#calling

Don`t include as_user param in chat.postEphemeral request if it is empty

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventType.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupArchiveEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupDeletedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupEventCore.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupOpenEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupRenameEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupUnarchiveEventIF.java

As slack actually sends us a lot more events, then we have now, and to satisfy need of having consumed events from private channels (so-called groups in the Slack API), this PR contains a few added models, which are also binded with the SlackEventType enum entries.
PR is ready for review.

Add models for group events

---

slack-base/src/main/java/com/hubspot/slack/client/models/auth/OAuthV2CredentialsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/users/SlackUserLiteIF.java
slack-base/src/test/resources/block_actions.json

In addition to bot token, we need to store user access token from Slack token request (oauth.v2.access) response on app installation.`OAuthV2CredentialsIF` model needs to be updated to get this token.

Add user access token to OAuth credentials model for V2 app

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelArchiveEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelCreatedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelDeletedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelRenameEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelUnarchiveEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/conversation/SlackConversationEventCore.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/conversation/SlackConversationEventWithChannel.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupArchiveEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupDeletedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupOpenEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupRenameEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/group/SlackGroupUnarchiveEventIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/events/json/EventDeserializerTest.java
slack-base/src/test/resources/group_archive_event.json
slack-base/src/test/resources/group_deleted_event.json
slack-base/src/test/resources/group_open_event.json
slack-base/src/test/resources/group_rename_event.json
slack-base/src/test/resources/group_unarchive_event.json

While working with this repo, I've discovered, that there are actually no general parent class, which will combine channel and group events, besides SlackEvent. 
For purposes of better compatibility, SlackConversationEventCore has been introduced.
Also, adding SlackConversationEventWithChannel, for those events, which require usage of full SlackChannel object, not only the id.

Update group and channel models. Add general SlackConversationEventCore model.

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/SectionIF.java

Currently, we are fetching text length `isTextLengthValid` before we check if the text is null and this results in an unnecessary NPE. This PR fixes the order of the checks.

Prevent NPEs in SectionIF check

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps
New apps currently can't use these methods.
We need to start sending all the tokens as Auth headers and not query params.

send slack token properly

---

slack-base/src/test/java/com/hubspot/slack/client/methods/params/chat/ChatDeleteParamsTest.java

Add integration test for `ChatDeleteParams` model to ensure that `as_user` param is not sent to Slack if it contains default value (`false`).
Slack doesn't allow to include `as_user` param in case if requests are executed by new granular bot.

Add integration test for ChatDeleteParams model

---

pom.xml

This updated the pinned immutables version to a slightly newer one which has the org.immutables:encode dep available. This is part of the rollout of https://github.com/HubSpot/hubspot-immutables/pull/19

Update to newer immutables version

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

`ObjectMapper` fails to serialize an instance of class `Object`. Because of this `getTeamInfo` method fails with 'No serializer found for class java.lang.Object'. since it passes `new Object()` as a `params` field to the `postSlackCommand` method. This PR fixes this by passing an empty map instead of the object's instance.

Fix 'No serializer found for class java.lang.Object' on getTeamInfo method execution

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/team/TeamInfoResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/teams/SlackTeamIF.java
slack-base/src/test/resources/block_actions.json
slack-base/src/test/resources/dialog_submission.json
slack-base/src/test/resources/interactive_button_click.json
slack-base/src/test/resources/interactive_load_options_req.json
slack-base/src/test/resources/view_submission.json

Added Slack team name to `SlackTeam` model to be able to get team name with [team.info](https://api.slack.com/methods/team.info#response) method.
Also, the `team.info` response doesn't contain the property `slack_team`. The corresponding JSON property is named `team`. This was fixed in the `TeamInfoResponse` model.

Add team name to SlackTeam model

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java

[conversations.create](https://api.slack.com/methods/conversations.create) API  returns this error if `a team preference prevents the authenticated user from creating channels`.

Add `restricted_action` error type

---

.github/workflows/ci.yml

It's required in `setup-java@v2.1.0`

Specify java distribution for GH action

---

slack-base/src/main/java/com/hubspot/slack/client/models/LiteMessageIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/ReactionIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/response/conversations/ConversationsRepliesResponseTest.java
slack-base/src/test/resources/conversations.replies.with_replies_and_new_fields.json

Added reactions to the `LiteMessage` model to be able to retrieve the list or reactions attached to a slack message.

Add reactions to conversation history

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/AbstractSlackEventBotMessage.java

Checking for an optional thread timestamp is how you verify if a message was posted in a thread or not. Without this you cannot disambiguate top level bot messages from threaded bot messages
@szabowexler

Add `thread_ts` field to bot messages

---

slack-base/pom.xml
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/ConversationSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ConversationsSelectMenuInputIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewConversationsSelectIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInput.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInputType.java
slack-base/src/test/resources/block_elements.json

Added [fields](https://api.slack.com/surfaces/modals/using#modal_response_url) for `ConversationsSelectMenu` model to receive channel id in the View Submission. Also added subtype of `ViewInput` type for the conversations-select input object unmarshalling.
Context: when the user selects the channel from [Conversations list](https://api.slack.com/reference/block-kit/block-elements#conversation_select) on the model, Slack sends are `conversations-select` object in the view submission `state` field (please see example below). In order to get the select channel, we need to have a corresponding model.
```
{
"type": "view_submission",
.
.
.
"callback_id": "callbackId",
"state": {
"values": {
.
.
.
"cdA=j": {
"conversation-select": {
"type": "conversations_select",
"selected_conversation": …
```

Add subtype for conversations-select input

---

slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackDialogFormTextElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormSelectElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormTextElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormTextareaElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/HasLabel.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/HasOptions.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackDialogFormElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackDialogFormElementLengthLimits.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionGroupIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/helper/SlackDialogElementNormalizer.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/helpers/SlackDialogElementNormalizer.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackDialogFormElementTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionsTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormTextElementTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormTextareaElementTest.java
slack-base/src/test/java/com/hubspot/slack/client/testutils/StringGenerator.java

I implemented normalization of the data that serves informational purposes - label, hint, a placeholder. We don't want to normalize stuff like `name` or `value` because their values can be used as unique identifiers and this can break the consumer in a very unexpected way.
Example of previous behavior: Let's assume that the element label is limited to 24 characters. If we set `aaaaaaaaaaaaaaaaaaaaaaaaaa`(26 chars long) as a label, the model is going to fail on the build.
Current behavior: We are going to show `aaaaaaaaaaaaaaaaaaaaaa...` instead to fit into the limit.

Normalize Slack form element presentational data

---

slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackDialogFormTextElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormSelectElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormTextElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormTextareaElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/HasLabel.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/HasOptions.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackDialogFormElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackDialogFormElementLengthLimits.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionGroupIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/helpers/SlackDialogElementNormalizer.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackDialogFormElementTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionsTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormTextElementTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormTextareaElementTest.java
slack-base/src/test/java/com/hubspot/slack/client/testutils/StringGenerator.java

Same as https://github.com/HubSpot/slack-client/pull/256 but fixed stackoverflow error during normalization caused by cyclic constructor calls in `with` methods.

Normalize Slack form element presentational data | Attempt 2

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/InputIF.java

`dispatch_action` field should be set to true for the [Input Block](https://api.slack.com/reference/block-kit/blocks#input) in order to be notified about user interaction with this block. E.g.: Slack will notify the app when the user selects an option from the select menu.

Add dispatch_action field to Input Block

---

slack-base/src/main/java/com/hubspot/slack/client/models/users/UserProfileIF.java
slack-base/src/test/resources/user_change.json

We've recently got `user_change` event with the user profile that has `status_expiration` equal `2841800400(year 2060)`. It isn't possible to set the expiration time like this in Slack app so I assume this was done via API. In order to avoid such issues in the future, I decided to change the type and hope that Slack won't allow setting something like `BigInteger` as `status_expiration` via API.

Change `UserProfile::statusExpiration` type to `long`

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/user/SlackMemberJoinedChannelEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/user/SlackMemberLeftChannelEventIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/events/json/EventDeserializerTest.java

Adding HasChannel to SlackMemberJoinedChannelEvent and SlackMemberLeftChannelEvent

HasChannel added to Leave and Join Events

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/BlockElementLengthLimits.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/InputIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/SlackBlockNormalizer.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/CheckboxesIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/PlainTextInputIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/RadioButtonGroupIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/StaticMultiSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/StaticSelectMenuIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/objects/OptionGroupIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/objects/OptionIF.java

Same as https://github.com/HubSpot/slack-client/pull/258 but for some of the BlockKit models.

Normalize some of blocks' presentational data

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/BlockElementLengthLimits.java

According to [this doc](https://api.slack.com/reference/block-kit/block-elements#datepicker), the max action ID length is 255 characters.

Add input action ID max length limit constant

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/Block.java

Support for deserializing the header block was missing.  This PR adds just that.

Add support for deserializing header block

---

slack-base/src/main/java/com/hubspot/slack/client/models/BaseSlackOptionsResponse.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlocksLoadOptionsResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/SlackOptionsResponseIF.java

SlackOptionsResponse model is needed to load Options to [Selects](https://api.slack.com/dialogs#select_elements) on [Slack Dialogs](https://api.slack.com/dialogs).

Add SlackOptionsResponse model for Dialog Options handling

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlockActionsIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/interaction/BlockActionsSerializationTest.java
slack-base/src/test/resources/block_actions_without_state.json

As per [Slack documentation](https://api.slack.com/reference/interaction-payloads/block-actions#fields) it sends either `state.values` or `view.state.values` so both of these fields should be `Optional` so we don't fail do parse the payload if one of them is missing.
`view.state.values` is sent on interactions with blocks inside of modal. 
`state.values` is sent on the interactions with blocks inside of the message.

Make `state` in `block_actions` payload optional

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/BlockElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/TimePickerIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewDatePickerIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInput.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewTimePickerIF.java
slack-base/src/test/resources/block_elements.json

Added support of `TimePicker` for BlockKit. Also added missing `getStringValue` for DatePicker and TimePicker to getting dates value in text format

Support `Timepicker` for BlockKit

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/TimePickerIF.java

Slack required set initial time in HH:mm format.
In this PR we change the initial time format to HH:mm

Change time picker initial time format

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/views/json/StateActionValueDeserializer.java

There are throws `DateTimeParseException` when trying to deserialize slack action with null initial date from the date picker.
In this PR we skip deserializing the date field with null initial values.

Fix DateTimeParseException when data field is null

---

slack-request-verifier/src/main/java/com/hubspot/slack/client/request/verifier/SlackRequestVerifier.java
slack-request-verifier/src/main/java/com/hubspot/slack/client/request/verifier/VerifySlackRequest.java

One of the two ways to implement a slack request verifier needs an annotation over the resource method and class that extends `SlackRequestVerifierFilter`, to prevent duplication of the annotations it's better to add this annotation to this project

add SlackRequestVerifier annotation

---

slack-base/src/main/java/com/hubspot/slack/client/models/SlackChannelIF.java

The field is added so that all channels stored in the cache could have `isShared` field, which will allow us to do filtering out shared channels, no matter if they are fetched from API or cache.

Add `isShared` field to `SlackChannel`.

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/Block.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/LinkIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/MessageBlock.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/RichBlockStyle.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/RichMessageBlock.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/RichTextIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/RichTextListIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/RichTextPreformattedIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/RichTextQuoteIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/RichTextSectionIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/TextIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/TextStyleIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/UserIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/blocks/messages/MessageActionSerializationTest.java
slack-base/src/test/resources/message_action.json
slack-base/src/test/resources/unknown_blocks.json

This PR adds message blocks, which are passed by Slack in the `message_action` payload. 
This will allow us to work with user messages in a much more sufficient way, removing the need to parse the Slack markdown text itself.

Add message blocks.

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/TextStyleIF.java

We broke the serialization of `TextStyleIF` in https://github.com/HubSpot/slack-client/pull/304 because if `Optional` is empty we pass `"code": null` to Slack and it returns us response like this:
```
{
"ok" : false,
"error" : "invalid_blocks",
"warning" : "missing_charset",
"response_metadata" : {
"messages" : [ "[ERROR] must be a boolean [json-pointer:/blocks/0/elements/0/elements/1/style/italic]", "[ERROR] must be a boolean [json-pointer:/blocks/0/elements/0/elements/1/style/strike]", "[ERROR] must be a boolean [json-pointer:/blocks/0/elements/0/elements/1/style/code]", "[ERROR] must be a boolean [json-pointer:/blocks/0/elements/0/elements/7/style/bold]", "[ERROR] must be a boolean [json-pointer:/blocks/0/elements/0/elements/7/style/italic]", "[ERROR] must be a boolean …
```

Default to `false` for text styles

---

slack-base/src/main/java/com/hubspot/slack/client/models/teams/SlackTeamIconIF.java

We used `image_original` field for the team's icon URL. It is not present on the [team](https://api.slack.com/methods/team.info) object anymore. I didn't found announcement about this in the [changelog](https://api.slack.com/changelog) so I don't know the reason why it was removed. 
I updated the `SlackTeamIconIF` model to use `image_88` instead.

Update Team icon URL field

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventWrapperIF.java

This PR adds ContextTeamId to SlackEventWrapper. I need this new field to extrude actual teamID for events that happened  in shared channels, since those events contains team ids for both workspaces. I made it optional because I don't want to break all the builds in the world. 
@zmarushchak-hs @omotnyk @motnyk @nliutyi-hs

Add ContextTeamId to SlackEventWrapper.

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackAccessDeniedFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackCsvFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackGifFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackJavaScriptFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackJpgFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackPngFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackTextFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/json/SlackFileDeserializer.java
slack-base/src/test/java/com/hubspot/slack/client/models/files/SlackFileDeserializerTest.java
slack-base/src/test/resources/file_gif.json
slack-base/src/test/resources/file_unknown_type.json
slack-base/src/test/resources/file_with_access_denied.json

Currently we fail to parse Slack response like below. This PR adds custom deserialiser to handle responses like this.
```
{
"id" : "F05RFJX6KL4",
"file_access" : "access_denied",
"created" : 0,
"timestamp" : 0,
"user" : "U01K1BQFK3R",
"filetype" : "png"
}
```

Support `"file_access": "access_denied"` in SlackFile model

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/TimePickerIF.java

This PR adds new optional field to timezone block, which, when set, will display a hint under the user's timepicker.

Add optional timezone field.

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackXlsFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackXlsxFileIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/files/SlackFileDeserializerTest.java
slack-base/src/test/resources/file_xls.json
slack-base/src/test/resources/file_xlsx.json

Been writing a job that generates a spreadsheet report and sends it to a slack channel. Without a proper type it reports in the slack UI as `Binary`. The file still works so this isn't blocking, but seems worthwhile to cover.
These types are in the [supported listing](https://api.slack.com/types/file#types). Let me know if I'm missing any related implementation details required to support this.

Add support for common spreadsheet file formats

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInputType.java

The following values are missing from the `ViewInputType` enum, causing those input types to be deserialized to "unknown". The enum is updated here so that the `ViewInput` objects can actually be built.
Note that `ViewInput` already includes the types `ViewEmailInput`, `ViewUrlInput`, `ViewNumberInput`, and `ViewDateTimePicker`.
Similar issue to https://github.com/HubSpot/slack-client/pull/271

Add additional view input types

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileTombstoneIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/json/SlackFileDeserializer.java
slack-base/src/test/java/com/hubspot/slack/client/models/files/SlackFileDeserializerTest.java
slack-base/src/test/resources/file_with_tombstone.json

Currently deserialization fails for responses with this shape:
```json
{
"messages" : [ {
"files" : [ {
"id" : "F04QS86SFML",
"mode" : "tombstone"
} ],
```
with error:
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
at com.hubspot.slack.client.models.files.json.SlackFileDeserializer.deserialize(SlackFileDeserializer.java:55)
at com.hubspot.slack.client.models.files.json.SlackFileDeserializer.deserialize(SlackFileDeserializer.java:24)
```

support deserializing empty files with mode="tombstone"

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java

There are a few errors which can be added to SlackErrorType. These error messages are returned for various [Conversations](https://api.slack.com/apis/conversations-api) methods.

added a few error types to SlackErrorType

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackConnectFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/json/SlackFileDeserializer.java
slack-base/src/test/java/com/hubspot/slack/client/models/files/SlackFileDeserializerTest.java
slack-base/src/test/resources/file_slack_connect.json

The current SlackFileDeserializer doesn't handle Slack Connect files, which are described [here in the docs](https://api.slack.com/events/message/file_share#slack_connect_files). This change adds support for these files.

Add support for deserializing Slack Connect files

---

slack-base/src/main/java/com/hubspot/slack/client/methods/SlackMethods.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/files/GetUploadURLExternalParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/files/GetUploadUrlExternalParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/files/GetUploadUrlExternalResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

I am adding a new Slack method [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) that was recently added by Slack

Add files.getUploadURLExternal method

---

slack-base/src/main/java/com/hubspot/slack/client/methods/SlackMethods.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/files/CompleteUploadExternalParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/files/FileIInfoIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/files/FileInfoIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/files/CompleteUploadExternalResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

I am adding a new Slack method [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal) that was recently added by Slack

Add files.completeUploadExternal method

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/ImageIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/SlackFileObjectIF.java

This adds support for the `slack_file` type in image blocks (docs [here](https://api.slack.com/reference/block-kit/composition-objects#slack_file)). This should allow usage of blocks that were uploaded using the [files API](https://api.slack.com/methods/files.getUploadURLExternal#markdown).

Add slack file object to image block

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/ImageIF.java

Image url is optional, according to [these docs](https://api.slack.com/reference/block-kit/blocks#image_fields).

Make url optional

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java

[not_in_channel](https://api.slack.com/methods/conversations.history#:~:text=The%20token%20used%20does%20not%20have%20access%20to%20the%20proper%20channel.%20Only%20user%20tokens%20can%20access%20public%20channels%20they%20are%20not%20in.) is one of the errors returned by Slack API. 
Need to have it to determine the reason why bot failed to set reaction to message sent by user. In such case we are going to show descriptive error message.

Add NOT_IN_CHANNEL Slack error type

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/SlackFileObjectIF.java

Missed this in https://github.com/HubSpot/slack-client/pull/358. This is needed so that only one of these two fields is serialized to json. If only one is present but both are serialized, it results in a "cannot parse attachment" error. [Docs here](https://api.slack.com/reference/block-kit/composition-objects#slack_file).

Fix json serialization for slack_files

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/DateTimePickerIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/EmailInputIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/NumberInputIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/UrlInputIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/users/SlackUserIF.java

Jackson serializes/deserializes getters with is* prefixes for Optional boolean values inconsistently across the versions Jackson. This will explictly add the de/serialization behaviour so that we can safely upgrade Jackson versions.

Add explict serializer and deserializer behaviour for is* getters

---

slack-base/src/main/java/com/hubspot/slack/client/methods/SlackMethods.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/assistant/PromptIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/assistant/SetSuggestedPromptsParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/assistant/SetThreadStatusParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/assistant/SetTitleParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventType.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/assistant/SlackAssistantThreadContextChangedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/assistant/SlackAssistantThreadStartedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/assistant/AssistantThreadContextIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/assistant/AssistantThreadIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

added methods & events to support[ Agents & Assistants](https://api.slack.com/partners/modern-ai-apps) app flow

Add Agents & Assistants models

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackZipFileIF.java

Add 'zip' filetype to the file type enum to handle zip files.
This PR is to resolve the same issue as the PR below does
https://github.com/HubSpot/slack-client/pull/364

add zip filetype

---

.github/workflows/ci.yml
pom.xml
slack-base/src/main/java/com/hubspot/slack/client/methods/SlackMethods.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/WorkObjectBase.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/WorkObjectIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/actions/WorkObjectActionBlockIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/actions/WorkObjectActionIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/actions/WorkObjectActionStyle.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/entity/EntityPayloadIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/entity/SlackEntityDetailsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/flexpane/FlexPaneMetadataIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/flexpane/MessageFormat.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/flexpane/WorkObjectFlexpaneErrorIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/flexpane/WorkObjectFlexpaneErrorStatus.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/workobject/flexpane/WorkObjectFlexpaneParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventType.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/links/EntityDetailsRequestedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/chat/EntityPresentDetailsResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java
slack-request-verifier/src/test/java/com.hubspot.slack.client.request.verifier/SlackRequestVerifierFilterTest.java

Description:
We, as the HubSpot Slack integration team, are continuing work on upgrading the link unfurling logic. We already support Work Objects and are going to extend this functionality further.
In this PR, I’ve added several models that will be used to add action buttons for Slack Work Objects and Flexpane, as well as to build the Work Object Flexpane itself. This PR also includes updates to the SlackClient to enable sending requests to the new entity.presentDetails Slack method.
Related issue: https://git.hubteam.com/HubSpot/slack-integration/issues/6303

Add models to deal with Slack Work Object Flexpane and Action Buttons for it
