HubSpot/slack-client

slack-base/src/main/java/com/hubspot/slack/client/methods/params/conversations/ConversationsInfoParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/conversations/ConversationIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/conversations/ConversationType.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/conversations/ConversationsInfoResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Adds support for [conversations.info](https://api.slack.com/methods/conversations.info)
@szabowexler

add support for conversations.info

---

README.md

correct group id

---

slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Similar to `SlackClient#getChannelByName`, this allows searching for a Conversation by name.
cc @darcatron

Add method to get conversation by name

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/reactions/ReactionsAddParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEvent.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/reactions/AddReactionResponseIF.java
slack-base/src/test/java/com/hubspot/slack/client/methods/params/reactions/ReactionsAddParamsTest.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Support for [reactions.add](https://api.slack.com/methods/reactions.add)
cc @dylanrb123

support adding reactions to messages

---

slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormTextareaElement.java

It's 3k now https://api.slack.com/dialogs#textarea_elements

update max length

---

slack-base/src/main/java/com/hubspot/slack/client/models/AttachmentIF.java

https://api.slack.com/docs/message-attachments

support image url in attachment

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/auth/AuthTestResponseIF.java

user and user id are optional in WTA response

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/SlackErrorType.java

add token revoked error

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/InteractiveCallbackType.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/MessageActionIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/SlackInteractiveCallback.java

Mostly allows for parsing `MESSAGE_ACTION` types: https://api.slack.com/actions
cc @szabowexler @dylanrb123

add support for app actions

---

README.md
slack-base/pom.xml
slack-base/src/main/java/com/hubspot/slack/client/methods/SlackMethods.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/conversations/ConversationsUserParamsIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

tested and it works fine
cc @szabowexler

support users.conversations

---

slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/AbstractSlackFormSelectElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionGroupIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/InteractiveLoadOptionsRequestIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/InteractiveLoadOptionsRequestType.java
slack-base/src/test/java/com/hubspot/slack/client/models/dialog/form/elements/SlackFormOptionsTest.java
slack-base/src/test/resources/interactive_load_options_req.json

https://api.slack.com/dialogs#dynamic_select_elements_external

add support for dynamic menus in dialogs

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackGifFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackTextFileIF.java

SlackFileTypes -> SlackFileType

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackCsvFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackGifFileIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackTextFileCore.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackTextFileIF.java

We can talk about the refactoring I did, but pushing this branch will allow me to start using it.
Depends on https://github.com/HubSpot/slack-client/pull/47
@szabowexler

 Add csv file type

---

README.md
slack-base/src/main/java/com/hubspot/slack/client/methods/params/auth/AuthRevokeParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/auth/AuthRevokeResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Auth revoke

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEventType.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelArchiveEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelCreatedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelDeletedEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelRenameEventIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/events/channel/SlackChannelUnarchiveEventIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/events/json/EventDeserializerTest.java
slack-base/src/test/resources/channel_archived_event.json
slack-base/src/test/resources/channel_created_message.json
slack-base/src/test/resources/channel_deleted_message.json
slack-base/src/test/resources/channel_renamed_event.json
slack-base/src/test/resources/channel_unarchived_event.json

Added new Slack events for `channel_created`, `channel_deleted`, `channel_archive`, `channel_unarchive`, and `channel_rename`

Channel events

---

slack-base/src/main/java/com/hubspot/slack/client/models/SlackChannelIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/ChannelDeserializerTest.java
slack-base/src/test/resources/general_channel.json

Also added a test to prove it deserializes properly with isGeneral set

Added isGeneral flag to SlackChannel 

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/channels/ChannelsKickParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/channels/ChannelsKickResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

This allows one to kick a user from a channel.

Add the ability to kick users from channels

---

slack-base/src/main/java/com/hubspot/slack/client/models/dialog/SlackDialogIF.java

Adds the state and the notify on cancel field for dialogs.
Documentation is here: https://api.slack.com/dialogs#submit
\cc @szabowexler

Adding state and notify on cancel to dialogs

---

pom.xml
slack-base/src/main/java/com/hubspot/slack/client/models/events/SlackEvent.java
slack-java-client-examples/pom.xml

Fix the build

---

slack-base/src/main/java/com/hubspot/slack/client/models/response/emoji/EmojiListResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Per the description, adds support for the [emoji.list](https://api.slack.com/methods/emoji.list) endpoint.

Add emoji list

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlockActionsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/SlackInteractiveCallback.java

Reverts the backward-incompatible change made in previous PR.

Add back in methods removed in a previous PR.

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatUnfurlParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/AttachmentIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/BlockOrAttachment.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/Block.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/chat/ChatUnfurlResponseIF.java
slack-base/src/test/java/com/hubspot/slack/client/ReflectionBasedFieldPresenceTest.java
slack-base/src/test/java/com/hubspot/slack/client/methods/params/chat/ChatUnfurlParamsTest.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Adds support for the [chat.unfurl](https://api.slack.com/methods/chat.unfurl) method from the Slack Web API

Add support for chat.unfurl method

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/chat/ChatUnfurlParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/json/BlockOrAttachmentDeserializer.java
slack-base/src/test/java/com/hubspot/slack/client/methods/params/chat/ChatUnfurlParamsTest.java
slack-base/src/test/resources/chat_unfurl_params_using_attachment.json
slack-base/src/test/resources/chat_unfurl_params_using_block.json

- Adds a custom deserializer for BlockOrAttachment
- Adds some unit tests for ser/des

Add deserializer for BlockOrAttachment

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/conversations/ConversationCreateParamsIF.java

Fix prop name

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/conversations/ConversationsJoinParamsIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Implemented `conversations.join` request.

Implmented conversations.join

---

README.md
slack-base/src/main/java/com/hubspot/slack/client/methods/params/conversations/ConversationSetPurposeParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/conversations/ConversationSetTopicParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/conversations/ConversationSetPurposeResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/conversations/ConversationSetTopicResponseIF.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Client methods for this Slack APIs:
- https://api.slack.com/methods/conversations.setTopic
- https://api.slack.com/methods/conversations.setPurpose

Add methods for setting topic/description

---

slack-base/src/main/java/com/hubspot/slack/client/models/users/SlackUserIF.java

Need to know if user is a bot or not.

Add @JsonProperty for isBot in SlackUserIF

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlockElementActionIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/json/BlockElementActionDeserializer.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/json/BlockElementActionSerializer.java

Action ID will be either provided or generated, but should always be present.

Action id will be included

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlocksLoadOptionsResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/InteractiveCallbackType.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/ShortcutIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/SlackInteractiveCallback.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/views/StateActionValueIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/views/json/StateActionValueDeserializer.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/views/json/StateActionValueSerializer.java
slack-base/src/test/resources/block_actions.json

Resolves issue #194, also includes support for dynamic external selectors and shortcut payloads

View state bug fix + misc

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlocksLoadOptionsResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/InteractiveCallbackType.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/ShortcutIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/SlackInteractiveCallback.java

To go along with `BlocksLoadOptionsRequestIF` which was already merged with PR #166.

Convenience class for dynamic URL select payload responses

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/SectionIF.java

Add precondition check that text length is valid in Section block

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/HeaderIF.java

Closes #190 
I modeled this off of `SectionIF.java` and the Header API described [here](https://api.slack.com/reference/block-kit/blocks#header). I'm very new to java, so any comments or suggestions would be very appreciated.

Add Header Block implementation

---

slack-base/src/main/java/com/hubspot/slack/client/models/events/AbstractSlackEventBotMessage.java

Need to read these out from bots that are posting using block-kit.

add-webhook-blocks

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/dnd/DndInfoParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/dnd/DndSetSnoozeParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/users/SetUserProfileParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/BlockElement.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/elements/CheckboxesIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/blocks/objects/OptionIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewCheckboxesIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInput.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInputType.java
slack-base/src/main/java/com/hubspot/slack/client/models/json/InstantDeserializer.java
slack-base/src/main/java/com/hubspot/slack/client/models/json/InstantSerializer.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/SimpleSlackResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/dnd/DndInfoResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/dnd/DndSnoozeResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/users/UserProfileIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/response/dnd/DndInfoResponseSerializationTest.java
slack-base/src/test/java/com/hubspot/slack/client/models/views/ViewSubmissionSerializationTest.java
slack-base/src/test/resources/block_elements.json
slack-base/src/test/resources/dnd_response_1.json
slack-base/src/test/resources/dnd_response_2.json
slack-base/src/test/resources/dnd_response_3.json
slack-base/src/test/resources/dnd_response_4.json
slack-base/src/test/resources/view_submission.json
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

This PR implements the users_profile_set API. I will add in test cases as soon as I get a moment :)

implements users_profile_set + dnd methods

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFile.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackJavaScriptFileIF.java

Added support for the new file type "javascript"

Added new file type for JavaScript files

---

slack-base/src/main/java/com/hubspot/slack/client/models/teams/SlackTeamIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/teams/SlackTeamIconIF.java

I need to get the icon URL for the Slack team. Added Icon field to the SlackTeam model.

Add Icon field to SlackTeam model

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInput.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewStaticSelectIF.java

Added model to be able to deserialize input provided by the static select element upon view submission.

Add static select view input model

---

slack-java-client-examples/README.md

test VS editor

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInput.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInputType.java
slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewMultiStaticSelectIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/views/ViewSubmissionSerializationTest.java
slack-base/src/test/resources/view_submission.json

I noticed that support of "multi_static_select" is missing, so I added it. Please review this as I'm not 100% sure that I added it in all needed places, hopefully didn't miss anything.

Added support of multi_static_select view

---

.github/workflows/ci.yml
slack-base/src/test/java/com/hubspot/slack/client/HasUserDeserializerTest.java

Trying to configure them once again.
Reverts HubSpot/slack-client#255

Enable GH actions CI

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/views/ViewInputType.java

Added missing ViewInputType for TimePicker

Add ViewInputType for TimePicker

---

slack-base/src/main/java/com/hubspot/slack/client/methods/SlackMethods.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/bookmarks/BookmarksAddParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/bookmarks/BookmarksEditParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/bookmarks/BookmarksListParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/bookmarks/BookmarksRemoveParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/bookmarks/BookmarkIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/bookmarks/BookmarkType.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/bookmarks/BookmarkAddResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/bookmarks/BookmarkEditResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/bookmarks/BookmarkListResponseIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/response/bookmarks/BookmarkRemoveResponseIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/response/bookmarks/BookmarkListResponseIFTest.java
slack-base/src/test/resources/bookmark_list_result.json
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java
slack-java-client/src/main/java/com/hubspot/slack/client/SlackWebClient.java

Adds support for:
* bookmarks.add
* bookmarks.edit
* bookmarks.remove
* bookmarks.list

Add bookmarks

---

slack-base/src/main/java/com/hubspot/slack/client/methods/params/calls/CallsAddParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/calls/CallsParticipantsAddParamsIF.java
slack-base/src/main/java/com/hubspot/slack/client/methods/params/calls/CallsParticipantsRemoveParamsIF.java

Small improvement to https://github.com/HubSpot/slack-client/pull/288

Immutables didn't like that

---

slack-base/src/main/java/com/hubspot/slack/client/models/calls/ExternalCallsUserIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/calls/SlackCallIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/calls/SlackCallsUserIF.java
slack-base/src/main/java/com/hubspot/slack/client/models/calls/SlackInternalOrExternalUser.java

These need snake case annotations.

Add snake case here

---

slack-base/src/main/java/com/hubspot/slack/client/models/interaction/BlockActionsIF.java
slack-base/src/test/java/com/hubspot/slack/client/models/interaction/BlockActionsSerializationTest.java
slack-base/src/test/resources/block_actions_with_message_container.json
slack-base/src/test/resources/block_actions_with_view_container.json
slack-base/src/test/resources/block_actions_without_container.json

Added Optional `container` field to BlockActions immutable object

Added container to block actions

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/EmojiIF.java

Reverts HubSpot/slack-client#300

Revert "Make the Emoji message block unicode field optional."

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/messages/TextStyleIF.java

Reverts HubSpot/slack-client#306

Revert "Default to `false` for text styles"

---

pom.xml
slack-base/pom.xml
slack-java-client-examples/pom.xml
slack-java-client-guice/pom.xml
slack-java-client/pom.xml
slack-request-verifier/pom.xml

Prepare for next development release.

bump version to 1.16.0-SNAPSHOT

---

README.md
slack-java-client/src/main/java/com/hubspot/slack/client/SlackClient.java

files.upload is now a deprecated method

Deprecate old methods

---

slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackFileType.java
slack-base/src/main/java/com/hubspot/slack/client/models/files/SlackGdocFileIF.java

Add 'gdoc' filetype to the file type enum to handle google docs

add gdoc filetype

---

pom.xml
slack-base/pom.xml
slack-java-client-examples/pom.xml
slack-java-client-guice/pom.xml
slack-java-client/pom.xml
slack-request-verifier/pom.xml

seems to be an issue in oss nexus with 1.16.5

bump version to 1.16.6

---

slack-base/src/main/java/com/hubspot/slack/client/models/blocks/Block.java

Amazingly this was missed 3 years ago when I added this. Allows deserializing from webhooks.

Add missing call subtype
